// DECLARE NEW VARIABLE WE USE LET
let javascriptIsFun = true;

console.log(javascriptIsFun); // true
console.log(typeof javascriptIsFun); // boolean
console.log(typeof 23); // number
console.log(typeof "Sonny"); // string

/* DYNAMIC TYPING */

// CHANGE VARIABLE WITHOUT LET - CHANGING CONTENT OF THE BOX
javascriptIsFun = "YES!";

console.log(typeof javascriptIsFun);

/*  ASSIGNMENT : DATA TYPES

1. Declare a variable called 'isIsland' and set its value according to your country. The variable should hold a Boolean value. Also declare a variable 'language', but don't assign it any value yet.

2. Log the types of 'isIsland', 'population', 'country' and 'language' to the console.

*/

let isIsland = false;
let language;

console.log(typeof isIsland, isIsland); 
console.log(typeof language);

