console.log("Sonny");

// Box analogy let [box = firstName] --> "Santino"
let firstName = "SANTINO";

// Variable Name [fistName] === "SANTINO"
console.log(firstName);

// camelCase Notation (keep it simple stick to camel case)


/*
LECTURE : VALUES AND VARIABLES
1. Declare variables called 'country', 'continent', and 'population' and assign their values according to your own country (population in millions)
2. Log their  variables to the console.
*/

let country = "United States of America";
let continent = "North America";
console.log(`COUNTRY: `,country); //United States of America
console.log(`CONTINENT: `,continent);//North America
